(()=>{
const LOGIN_V3='https://www.spxos.com.br/entrar';
const app=document.querySelector('#app');
const route=(new URLSearchParams(location.search).get('route')||location.pathname).replace(/^\/+|\/+$/g,'');
const supported=['produto','solucoes','sobre','planos'];
if(!app||!supported.includes(route)) return;

const cta=(title)=>`<section class="final-cta"><div class="wrap final-cta-inner"><div><h2>${title}</h2><p>Clientes ativos acessam o ambiente protegido do SPX OS em spxos.com.br.</p></div><a class="button button-light" href="${LOGIN_V3}">Acessar plataforma</a></div></section>`;
const stage=(title,subtitle,content,extra='')=>`<div class="v3-stage ${extra}"><div class="v3-stage-top"><div><strong>${title}</strong> <span>${subtitle||''}</span></div><span class="v3-live">Demonstração</span></div>${content}</div>`;

const crmDemo=()=>stage('Jornada comercial','próxima ação visível',`<div class="crm-demo"><div class="crm-toolbar"><div><span class="crm-filter">Todos os procedimentos</span><span class="crm-filter">Todos os responsáveis</span></div><button class="crm-new">+ Nova oportunidade</button></div><div class="crm-flow"><span class="crm-flow-progress"></span>${[
['Novo lead','18','R$ 146.300'],['Contato','12','R$ 92.800'],['Qualificação','20','R$ 178.700'],['Agendamento','14','R$ 116.800'],['Proposta','9','R$ 84.900'],['Fechamento','64','R$ 184.250']
].map((x,i)=>`<div class="crm-stage-node" data-crm-stage="${i}"><small>${x[0]}</small><b>${x[1]} oportunidades</b><strong>${x[2]}</strong><em>potencial / valor no exemplo</em></div>`).join('')}<div class="crm-lead-card"><header><span class="crm-lead-avatar">AC</span><div><b>Aline Cardoso</b><small>Ortodontia Invisível</small></div></header><footer><span class="crm-card-status">Novo lead</span><strong class="crm-card-value">R$ 12.900</strong></footer></div></div><div class="crm-caption"><div><small>ORIGEM</small><strong>WhatsApp</strong></div><div><small>RESPONSÁVEL</small><strong>Comercial</strong></div><div><small>PRÓXIMO MOVIMENTO</small><strong class="crm-next">Realizar contato</strong></div></div></div>`,'crm-live');

const waDemo=()=>stage('WhatsApp integrado','conversa + contexto comercial',`<div class="wa-demo"><aside class="wa-list"><div class="wa-list-head"><b>Central WhatsApp</b><span>Conversas dentro da operação</span></div>${[['JP','Juliana Pereira','Gostaria de agendar uma avaliação.'],['BH','Bruno Henrique','Qual seria o valor do tratamento?'],['TR','Thiago Ramos','Vou confirmar e retorno.'],['AC','Aline Cardoso','Tenho interesse em uma avaliação.']].map((x,i)=>`<div class="wa-contact ${i===0?'active':''}"><span class="wa-avatar">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}</aside><section class="wa-thread"><div class="wa-thread-head"><span class="wa-avatar">JP</span><div><b>Juliana Pereira</b><small>Implante Unitário</small></div></div><div class="wa-messages"><div class="wa-msg in">Olá! Gostaria de agendar uma avaliação.</div><div class="wa-msg out">Olá, Juliana. Vamos agendar sim. Qual o melhor dia e horário?</div><div class="wa-msg in">Terça-feira pela manhã seria ótimo.</div><div class="wa-typing"><i></i><i></i><i></i></div><div class="wa-msg out">Perfeito. Temos disponibilidade terça-feira às 10h. Posso reservar?</div><div class="wa-msg in">Pode sim. Obrigada!</div><div class="wa-msg out">Agendamento confirmado para terça-feira às 10h. ✅</div></div><div class="wa-compose">Digite sua mensagem…</div></section><aside class="wa-context"><strong>Contexto da oportunidade</strong><div class="wa-field"><small>Etapa atual</small><span class="wa-status">Contato</span></div><div class="wa-field"><small>Procedimento</small><span>Implante Unitário</span></div><div class="wa-field"><small>Responsável</small><span>Gustavo Pereira</span></div><div class="wa-field"><small>Próxima ação</small><span class="wa-next">Confirmar disponibilidade</span></div><div class="wa-check"><i>✓</i>Contato inicial</div><div class="wa-check"><i></i>Agendamento realizado</div><div class="wa-check"><i></i>Avaliação concluída</div></aside></div>`,'wa-live');

const perfDemo=()=>stage('Desempenho','o caminho da oportunidade',`<div class="perf-demo"><div class="perf-kpis">${[['Oportunidades','412'],['Avaliações','176'],['Fechamentos','64'],['Valor fechado','R$ 184.250']].map(x=>`<div class="perf-kpi"><small>${x[0]}</small><strong data-counter="${x[1].replace(/\D/g,'')||0}" data-display="${x[1]}">0</strong></div>`).join('')}</div><div class="perf-funnel">${[['LEADS','412','64,6%'],['CONTATADOS','266','62,4%'],['AGENDADOS','166','61,4%'],['COMPARECERAM','102','62,7%'],['FECHARAM','64','']].map((x,i)=>`<div class="perf-step ${i===2?'attention':''}"><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('')}</div><div class="perf-charts"><div class="perf-card"><strong>Canais com mais oportunidades</strong>${[['WhatsApp',92,198],['Indicação',66,132],['Instagram',28,48],['Google',20,34]].map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="bar-track"><div class="bar-fill" data-width="${x[1]}%"></div></div><b>${x[2]}</b></div>`).join('')}</div><div class="perf-card"><strong>Fechamentos por procedimento</strong>${[['Implante',88,18],['Prótese',74,15],['Lentes',59,12],['Aparelho',44,9]].map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="bar-track"><div class="bar-fill" data-width="${x[1]}%"></div></div><b>${x[2]}</b></div>`).join('')}</div></div><div class="perf-alert"><div><small>MAIOR PONTO DE ATENÇÃO</small><strong>Agendados · 61,4% de conversão</strong></div><span>Investigar confirmação e no-show antes de aumentar volume.</span></div></div>`,'perf-live');

const unitDemo=()=>stage('Multiunidade','governança por organização e unidade',`<div class="unit-demo"><div class="unit-tabs">${['Consolidado','Matriz','Unidade 2','Unidade 3'].map((x,i)=>`<button class="unit-tab ${i===0?'active':''}" data-unit="${i}">${x}</button>`).join('')}</div><div class="unit-kpis"><div class="unit-kpi"><small>Oportunidades</small><strong data-unit-kpi="leads">412</strong></div><div class="unit-kpi"><small>Fechamentos</small><strong data-unit-kpi="closed">64</strong></div><div class="unit-kpi"><small>Valor fechado</small><strong data-unit-kpi="value">R$ 184.250</strong></div></div><div class="unit-grid"><div class="unit-card"><strong>Equipe e responsabilidades</strong>${[['MC','Mariana Costa','34,0%'],['RS','Rafael Silva','29,1%'],['TS','Thiago Santos','24,6%'],['AC','Aline Cardoso','21,3%']].map(x=>`<div class="team-row"><i>${x[0]}</i><span>${x[1]}</span><b>${x[2]}</b></div>`).join('')}</div><div class="unit-card"><strong>Governança ativa</strong><div class="governance-row"><span>Distribuição por unidade</span><em>Ativa</em></div><div class="governance-row"><span>Round Robin</span><em>Ativa</em></div><div class="governance-row"><span>Por capacidade</span><em>Ativa</em></div><div class="governance-row"><span>Acessos por função</span><em>Ativa</em></div></div></div></div>`,'unit-live');

const marketingDemo=()=>stage('Marketing','da origem ao avanço comercial',`<div class="solution-demo"><div class="flow-sources"><div class="source-list">${[['WhatsApp','198'],['Indicação','132'],['Instagram','48'],['Google','34']].map(x=>`<div class="source-chip"><span><i></i> ${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="source-pipeline"><span class="flow-dot"></span>${[['Entrada','412'],['Contato','266'],['Agendamento','166'],['Fechamento','64']].map((x,i)=>`<div class="flow-node ${i===0?'active':''}" data-flow-node="${i}"><i></i><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div></div></div>`,'marketing-live');

const commercialDemo=()=>stage('Comercial','o que precisa de atenção agora',`<div class="solution-demo"><div class="daily-demo"><div class="daily-column"><strong>Prioridades do dia</strong>${[['↗','Interesses sem agenda','14 oportunidades'],['◷','Retornos vencidos','6 pendências'],['▣','A confirmar','9 avaliações'],['!','Faltosos','4 pacientes']].map((x,i)=>`<div class="task-card ${i===0?'focus':''}" data-task="${i}"><i>${x[0]}</i><div><b>${x[1]}</b><small>${x[2]}</small></div><em>${i<2?'Ação':'Hoje'}</em></div>`).join('')}</div><div class="daily-column"><strong>Próximos acompanhamentos</strong>${[['09:00','Juliana Becker','Qualificação'],['11:00','Bruno Henrique','Retorno'],['13:00','Isabela Castro','Acompanhamento'],['15:30','Lucas Fernandes','Proposta']].map(x=>`<div class="task-card"><i>${x[0].slice(0,2)}</i><div><b>${x[1]}</b><small>${x[2]}</small></div><em>${x[0]}</em></div>`).join('')}</div></div></div>`,'commercial-live');

const execDemo=()=>stage('Diretoria','uma leitura executiva por recorte',`<div class="exec-demo"><div class="exec-filter">${['Consolidado','Canal','Procedimento','Responsável'].map((x,i)=>`<button class="${i===0?'active':''}" data-exec="${i}">${x}</button>`).join('')}</div><div class="exec-kpis"><div><small>Oportunidades</small><strong data-exec-kpi="0">412</strong></div><div><small>Conversão final</small><strong data-exec-kpi="1">15,5%</strong></div><div><small>Valor fechado</small><strong data-exec-kpi="2">R$ 184.250</strong></div></div><div class="exec-chart">${[76,58,88,46,68,53].map((x,i)=>`<div class="exec-bar" style="height:${x}%" data-base="${x}"><span>${['Jan','Fev','Mar','Abr','Mai','Jun'][i]}</span></div>`).join('')}</div></div>`,'exec-live');

const networkDemo=()=>stage('Redes e filiais','comparar sem perder o consolidado',`<div class="network-demo"><div class="network-map">${[['Matriz','412 oportunidades','Principal operação'],['Unidade 2','127 oportunidades','Equipe local'],['Unidade 3','86 oportunidades','Equipe local'],['Consolidado','3 unidades','Uma leitura comum']].map((x,i)=>`<div class="unit-box ${i===0?'active':''}" data-network="${i}"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</div><aside class="network-summary"><small>VISÃO CONSOLIDADA</small><strong>3 unidades</strong><hr><p>Mesma jornada comercial</p><p>Regras e acessos por função</p><p>Leitura de desempenho por unidade</p><p>Padronização de cadastros</p></aside></div>`,'network-live');

const architectureDemo=()=>stage('Arquitetura SPX OS','da oportunidade à decisão',`<div class="architecture-demo">${[
['01 · OPERAÇÃO','Entrada e execução','Jornada, conversa, agenda, acompanhamento e responsabilidade.'],['02 · LEITURA','Desempenho','Conversão, perdas, canal, procedimento, responsável e unidade.'],['03 · GOVERNANÇA','Direção','Regras, acessos, distribuição, padronização e visão executiva.']
].map((x,i)=>`<div class="arch-layer ${i===0?'active':''}" data-arch="${i}"><small>${x[0]}</small><strong>${x[1]}</strong><p>${x[2]}</p></div>`).join('')}</div>`,'dark');

const resolverDemo=()=>`<div class="question-resolver">${[
['Quem gerou a oportunidade?','Origem registrada'],['Quem ficou responsável?','Responsabilidade definida'],['Onde ela parou?','Etapa visível'],['Quanto avançou?','Conversão mensurada'],['O que precisa acontecer agora?','Próxima ação clara']
].map((x,i)=>`<div class="resolver-row" data-resolver="${i}"><i>?</i><strong>${x[0]}</strong><span>${x[1]} ✓</span></div>`).join('')}</div>`;

const planEvolution=()=>stage('Evolução da operação','estrutura proporcional à complexidade',`<div class="plan-evolution"><div class="plan-track"><span class="plan-progress"></span>${[['01','Operação','Organizar uma equipe'],['02','Gestão','Marketing + Comercial'],['03','Escala','Redes e filiais']].map((x,i)=>`<div class="plan-level ${i===0?'active':''}" data-plan="${i}"><i>${x[0]}</i><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div><div class="plan-detail-live"><div class="plan-detail-copy"><small data-plan-label>OPERAÇÃO</small><h3 data-plan-title>Organize a rotina comercial.</h3><p data-plan-desc>Para empresas que precisam centralizar jornada, atendimento e acompanhamento em uma única operação.</p></div><div class="plan-feature-live">${['CRM Comercial','Jornada e agenda','WhatsApp integrado','Indicadores operacionais','Desempenho e conversão','Regras de distribuição','Automações','Multiunidade','Governança por função','Padronização entre filiais'].map((x,i)=>`<span data-feature="${i}" class="${i<4?'on':''}">${x}</span>`).join('')}</div></div></div>`,'plans-live');

const productPage=()=>`<div class="v3-page"><section class="v3-hero"><div class="wrap v3-hero-grid"><div class="v3-hero-copy"><p class="eyebrow">PRODUTO</p><h1>Uma operação comercial que mostra o próximo movimento.</h1><p>O SPX OS conecta jornada, conversa, desempenho e governança. Cada módulo existe para reduzir o espaço entre informação e ação.</p><div class="v3-actions"><a class="button button-primary" href="${LOGIN_V3}">Acessar SPX OS</a><a class="button button-quiet" href="#crm">Explorar o produto</a></div></div>${crmDemo()}</div></section><div class="v3-divider"></div>
<section class="v3-section" id="crm"><div class="wrap v3-section-head"><div><p class="eyebrow">CRM COMERCIAL</p><h2>Da entrada ao fechamento, cada oportunidade precisa carregar contexto.</h2></div><p>O CRM não funciona como uma lista de nomes. Ele organiza estágio, origem, unidade, procedimento, responsável, potencial financeiro e próxima ação — e torna o avanço visível para a equipe.</p></div><div class="wrap">${crmDemo()}</div></section>
<section class="v3-section soft" id="whatsapp"><div class="wrap v3-split reverse">${waDemo()}<div class="v3-copy"><p class="eyebrow">WHATSAPP INTEGRADO</p><h2>A conversa muda a operação enquanto acontece.</h2><p>À medida que o atendimento avança, etapa, próxima ação e checklist deixam de depender da memória do atendente. A conversa permanece ligada ao contexto comercial.</p><ul class="v3-points"><li>Central de conversas por status</li><li>Ficha da oportunidade ao lado do atendimento</li><li>Templates e atalhos operacionais</li><li>Movimentação de etapa e retorno sem trocar de ambiente</li></ul></div></div></section>
<section class="v3-section" id="desempenho"><div class="wrap v3-section-head"><div><p class="eyebrow">DESEMPENHO</p><h2>O dado deixa de ser relatório e passa a apontar onde investigar.</h2></div><p>A jornada mostra o que entrou, o que avançou e onde a conversão caiu. Canal, procedimento e responsável completam a leitura para que a gestão não dependa de feeling.</p></div><div class="wrap">${perfDemo()}</div></section>
<section class="v3-section soft" id="multiunidade"><div class="wrap v3-split"><div class="v3-copy"><p class="eyebrow">MULTIUNIDADE</p><h2>Uma estrutura para crescer sem perder padrão.</h2><p>A visão pode mudar por unidade sem perder o consolidado. Regras, acessos, distribuição e responsabilidades continuam sob a mesma arquitetura operacional.</p><ul class="v3-points"><li>Organização e unidade como contexto</li><li>Distribuição por regra</li><li>Acessos por função</li><li>Cadastros e automações centralizados</li></ul></div>${unitDemo()}</div></section>${cta('Conheça o produto por dentro. Depois deixe a operação falar por ele.')}</div>`;

const solutionsPage=()=>`<div class="v3-page"><section class="v3-hero"><div class="wrap v3-hero-grid"><div class="v3-hero-copy"><p class="eyebrow">SOLUÇÕES</p><h1>A mesma operação vista por quem gera, quem vende e quem decide.</h1><p>O SPX OS não cria verdades diferentes para cada área. Ele organiza a mesma jornada para que Marketing, Comercial, Diretoria e Redes enxerguem o recorte que precisam.</p><div class="v3-actions"><a class="button button-primary" href="#marketing">Explorar soluções</a></div></div>${marketingDemo()}</div></section>
<section class="v3-section" id="marketing"><div class="wrap v3-split"><div class="v3-copy"><p class="eyebrow">MARKETING</p><h2>O lead não termina quando entra. Ele precisa ser acompanhado até o avanço comercial.</h2><p>Origem e volume ganham contexto quando o marketing consegue enxergar contato, agendamento e fechamento dentro da mesma jornada.</p><ul class="v3-points"><li>Fontes e origens centralizadas</li><li>Leitura do avanço depois da entrada</li><li>Procedimento e potencial associados</li><li>Uma visão comum com vendas</li></ul></div>${marketingDemo()}</div></section>
<section class="v3-section soft" id="comercial"><div class="wrap v3-split reverse">${commercialDemo()}<div class="v3-copy"><p class="eyebrow">COMERCIAL</p><h2>A operação começa pelo que exige atenção agora.</h2><p>Interesses sem agenda, retornos vencidos, confirmações e faltosos deixam de ficar escondidos em históricos e passam a funcionar como trabalho organizado.</p><ul class="v3-points"><li>Prioridades do dia</li><li>Follow-up e retornos</li><li>Agenda e confirmação</li><li>Responsabilidade por oportunidade</li></ul></div></div></section>
<section class="v3-section" id="diretoria"><div class="wrap v3-split"><div class="v3-copy"><p class="eyebrow">DIRETORIA</p><h2>Uma leitura executiva que muda de recorte sem perder o todo.</h2><p>Volume, conversão, fechamento e receita podem ser lidos pelo consolidado e investigados por canal, procedimento e responsável.</p><ul class="v3-points"><li>Conversão entre etapas</li><li>Receita e fechamento</li><li>Ponto de atenção operacional</li><li>Recortes por responsável, canal e procedimento</li></ul></div>${execDemo()}</div></section>
<section class="v3-section soft" id="redes"><div class="wrap v3-split reverse">${networkDemo()}<div class="v3-copy"><p class="eyebrow">REDES E FILIAIS</p><h2>Várias unidades sem virar várias operações desconectadas.</h2><p>Cada unidade mantém seu contexto enquanto a direção conserva uma leitura comum da jornada, das regras e do desempenho.</p><ul class="v3-points"><li>Visão por unidade</li><li>Consolidado de rede</li><li>Governança por função</li><li>Padronização de processo</li></ul></div></div></section>${cta('Marketing, comercial e gestão olhando para a mesma operação.')}</div>`;

const aboutPage=()=>`<div class="v3-page"><section class="about-hero"><div class="wrap about-grid"><div><p class="eyebrow gold">SOBRE O SPX OS</p><h1>O sistema surgiu para uma coisa: trazer clareza para a operação.</h1></div><div><p>Empresas não sofrem apenas por falta de informação. Sofrem quando marketing, vendas e gestão enxergam pedaços diferentes da mesma realidade.</p><p>O SPX OS nasceu para reduzir esse espaço.</p></div></div></section>
<section class="v3-section"><div class="wrap v3-section-head"><div><p class="eyebrow">A ORIGEM</p><h2>Trocar pontos de interrogação por pontos finais.</h2></div><p>A proposta não é adicionar mais um dashboard. É fazer perguntas operacionais deixarem de depender de memória, reunião ou planilha paralela.</p></div><div class="wrap">${resolverDemo()}</div></section>
<section class="v3-section dark"><div class="wrap v3-section-head"><div><p class="eyebrow gold">COMO O SISTEMA GANHA FORMA</p><h2>Operação, leitura e governança na mesma arquitetura.</h2></div><p>O software materializa o princípio da SPX: integrar marketing, vendas e dados para organizar leitura, responsabilidade e direção.</p></div><div class="wrap">${architectureDemo()}</div></section>
<section class="v3-section soft"><div class="wrap v3-split"><div class="v3-copy"><p class="eyebrow">PRINCÍPIO SPX</p><h2>“Feeling é ego. Clareza é certeza.”</h2><p>Clareza aparece quando a empresa consegue responder quem gerou, quem assumiu, onde parou, quanto avançou e o que precisa acontecer agora — sem reconstruir o contexto toda vez.</p></div><div class="questions"><p><span>01</span> Marketing registra a entrada.</p><p><span>02</span> Comercial assume a execução.</p><p><span>03</span> O sistema acompanha a jornada.</p><p><span>04</span> Gestão lê conversão e perdas.</p><p><span>05</span> Governança sustenta o padrão.</p></div></div></section>${cta('Clareza não é um dashboard. É saber o que fazer com a operação.')}</div>`;

const plansPage=()=>`<div class="v3-page"><section class="v3-hero"><div class="wrap v3-hero-grid"><div class="v3-hero-copy"><p class="eyebrow">PLANOS</p><h1>O sistema cresce junto da complexidade da operação.</h1><p>Uma empresa com uma equipe não precisa da mesma governança de uma rede com múltiplas unidades. A estrutura acompanha o nível de operação, gestão e escala.</p><div class="v3-actions"><a class="button button-primary" href="#planos-v3">Ver estrutura dos planos</a></div></div>${planEvolution()}</div></section>
<section class="v3-section" id="planos-v3"><div class="wrap v3-section-head"><div><p class="eyebrow">ESCOLHA POR MATURIDADE</p><h2>Mais complexidade só entra quando a operação realmente precisa.</h2></div><p>A composição abaixo apresenta a lógica de evolução do produto. Valores, limites exatos de usuários, unidades e automações continuam sob definição comercial.</p></div><div class="wrap">${planEvolution()}</div></section>
<section class="v3-section soft"><div class="wrap pricing-grid"><article><div><small>OPERAÇÃO</small><h2>Organizar uma equipe comercial.</h2><p>Para centralizar jornada, atendimento e rotina em um único lugar.</p></div><ul><li>CRM Comercial</li><li>Jornada e agenda</li><li>WhatsApp integrado</li><li>Indicadores operacionais</li></ul><div class="plan-close"><strong>Configuração sob proposta</strong><span>Para operações menores e em estruturação.</span></div></article><article class="featured"><div><small>GESTÃO</small><h2>Marketing e comercial operando juntos.</h2><p>Para adicionar desempenho, regras, distribuição e maior leitura gerencial.</p></div><ul><li>Tudo do plano Operação</li><li>Desempenho e conversão</li><li>Regras de distribuição</li><li>Automações e configurações</li><li>Mais equipes e responsabilidades</li></ul><div class="plan-close"><strong>Configuração sob proposta</strong><span>Para empresas em crescimento e maior maturidade comercial.</span></div></article><article><div><small>ESCALA</small><h2>Redes, filiais e maior governança.</h2><p>Para múltiplas unidades, acessos por função e padronização da operação.</p></div><ul><li>Tudo do plano Gestão</li><li>Multiunidade</li><li>Governança por função</li><li>Padronização entre filiais</li><li>Implantação orientada à estrutura</li></ul><div class="plan-close"><strong>Configuração sob proposta</strong><span>Para operações complexas, redes e grupos empresariais.</span></div></article></div><div class="wrap pricing-note"><p>Os limites exatos de usuários, unidades, automações e integrações devem ser definidos comercialmente antes de publicar uma tabela definitiva.</p></div></section>${cta('O plano certo começa pelo desenho da sua operação.')}</div>`;

const pages={produto:productPage,solucoes:solutionsPage,sobre:aboutPage,planos:plansPage};
app.innerHTML=pages[route]();

/* Intersection reveals */
const revealTargets=[...app.querySelectorAll('.v3-section-head,.v3-copy,.v3-stage,.question-resolver,.pricing-grid article')];
revealTargets.forEach((el,i)=>{el.classList.add('v3-reveal');el.style.transitionDelay=`${Math.min(i%3,2)*.05}s`;});
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}}),{threshold:.12,rootMargin:'0px 0px -8% 0px'});
revealTargets.forEach(el=>io.observe(el));

/* CRM animation */
const crmStages=[...app.querySelectorAll('[data-crm-stage]')];
if(crmStages.length){let i=0;const card=app.querySelector('.crm-lead-card'),progress=app.querySelector('.crm-flow-progress'),status=app.querySelector('.crm-card-status'),next=app.querySelector('.crm-next');const statuses=['Novo lead','Contato iniciado','Em qualificação','Avaliação agendada','Proposta enviada','Fechado'];const nexts=['Realizar contato','Qualificar interesse','Agendar avaliação','Realizar avaliação','Acompanhar proposta','Relacionamento'];const tick=()=>{crmStages.forEach((x,j)=>x.classList.toggle('active',j===i));if(progress)progress.style.width=`${i*18}%`;if(card){card.style.left=`calc(${i*18}% + 1%)`;card.style.top=i%2? '78px':'70px';}if(status)status.textContent=statuses[i];if(next)next.textContent=nexts[i];i=(i+1)%crmStages.length};tick();setInterval(tick,2200);}

/* WhatsApp animation */
const messages=[...app.querySelectorAll('.wa-msg')];
if(messages.length){let m=0;const typing=app.querySelector('.wa-typing'),status=app.querySelector('.wa-status'),next=app.querySelector('.wa-next'),checks=[...app.querySelectorAll('.wa-check')];const step=()=>{if(m>=messages.length){messages.forEach(x=>x.classList.remove('show'));checks.forEach((x,i)=>x.classList.toggle('done',i===0));if(status)status.textContent='Contato';if(next)next.textContent='Confirmar disponibilidade';m=0;return;}if(m===3&&typing){typing.classList.add('show');setTimeout(()=>typing.classList.remove('show'),700);}messages[m].classList.add('show');if(m>=3){if(status)status.textContent='Agendamento';if(next)next.textContent='Confirmar avaliação';checks[1]?.classList.add('done');}m++;};step();setInterval(step,1050);}

/* Counters and bars */
const perf=app.querySelector('.perf-live');
if(perf){const pio=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;app.querySelectorAll('.bar-fill').forEach((b,i)=>setTimeout(()=>b.style.width=b.dataset.width,100+i*80));app.querySelectorAll('[data-counter]').forEach(el=>{const display=el.dataset.display;if(display.includes('R$')){let n=0,target=184250;const t=setInterval(()=>{n+=15354;if(n>=target){n=target;clearInterval(t);}el.textContent='R$ '+n.toLocaleString('pt-BR');},35);}else{let n=0,target=Number(el.dataset.counter);const t=setInterval(()=>{n+=Math.ceil(target/22);if(n>=target){n=target;clearInterval(t);}el.textContent=n.toLocaleString('pt-BR');},28);}});pio.disconnect();}),{threshold:.3});pio.observe(perf);}

/* Unit switcher */
const unitTabs=[...app.querySelectorAll('.unit-tab')];
if(unitTabs.length){const data=[['412','64','R$ 184.250'],['198','31','R$ 89.600'],['127','19','R$ 55.400'],['87','14','R$ 39.250']];let u=0;const setUnit=(idx)=>{u=idx;unitTabs.forEach((x,i)=>x.classList.toggle('active',i===u));['leads','closed','value'].forEach((k,i)=>{const el=app.querySelector(`[data-unit-kpi="${k}"]`);if(el)el.textContent=data[u][i];});};unitTabs.forEach((x,i)=>x.addEventListener('click',()=>setUnit(i)));setInterval(()=>setUnit((u+1)%unitTabs.length),3300);}

/* Marketing flow */
const flowNodes=[...app.querySelectorAll('[data-flow-node]')];
if(flowNodes.length){let f=0;const dot=app.querySelector('.flow-dot');const ftick=()=>{flowNodes.forEach((x,i)=>x.classList.toggle('active',i===f));if(dot)dot.style.left=`${8+f*28}%`;f=(f+1)%flowNodes.length};ftick();setInterval(ftick,1900);}

/* Commercial priorities */
const tasks=[...app.querySelectorAll('[data-task]')];
if(tasks.length){let t=0;setInterval(()=>{tasks.forEach((x,i)=>x.classList.toggle('focus',i===t));t=(t+1)%tasks.length;},1800);}

/* Executive filters */
const execBtns=[...app.querySelectorAll('[data-exec]')];
if(execBtns.length){const vals=[['412','15,5%','R$ 184.250'],['198','18,2%','R$ 91.400'],['176','19,8%','R$ 108.600'],['64','34,0%','R$ 184.250']];const heights=[[76,58,88,46,68,53],[44,68,55,82,61,74],[61,48,77,56,86,64],[52,73,44,82,67,58]];let e=0;const setExec=(idx)=>{e=idx;execBtns.forEach((x,i)=>x.classList.toggle('active',i===e));app.querySelectorAll('[data-exec-kpi]').forEach((x,i)=>x.textContent=vals[e][i]);app.querySelectorAll('.exec-bar').forEach((x,i)=>x.style.height=`${heights[e][i]}%`);};execBtns.forEach((x,i)=>x.addEventListener('click',()=>setExec(i)));setInterval(()=>setExec((e+1)%execBtns.length),3600);}

/* Network focus */
const network=[...app.querySelectorAll('[data-network]')];
if(network.length){let n=0;setInterval(()=>{network.forEach((x,i)=>x.classList.toggle('active',i===n));n=(n+1)%network.length;},2100);}

/* Architecture + resolver */
const arch=[...app.querySelectorAll('[data-arch]')];
if(arch.length){let a=0;setInterval(()=>{arch.forEach((x,i)=>x.classList.toggle('active',i===a));a=(a+1)%arch.length;},2100);}
const resolver=[...app.querySelectorAll('[data-resolver]')];
if(resolver.length){let r=0;setInterval(()=>{resolver[r]?.classList.add('resolved');const icon=resolver[r]?.querySelector('i');if(icon)icon.textContent='✓';r++;if(r>=resolver.length)setTimeout(()=>{resolver.forEach(x=>{x.classList.remove('resolved');const q=x.querySelector('i');if(q)q.textContent='?';});r=0;},2200);},900);}

/* Plan evolution */
const planLevels=[...app.querySelectorAll('[data-plan]')];
if(planLevels.length){const plans=[{label:'OPERAÇÃO',title:'Organize a rotina comercial.',desc:'Para empresas que precisam centralizar jornada, atendimento e acompanhamento em uma única operação.',features:4},{label:'GESTÃO',title:'Conecte marketing, comercial e gestão.',desc:'Adiciona desempenho, distribuição, automações e uma leitura gerencial mais completa.',features:7},{label:'ESCALA',title:'Cresça com governança entre unidades.',desc:'Amplia a estrutura para múltiplas unidades, acessos por função e padronização entre filiais.',features:10}];let p=0;const setPlan=(idx)=>{p=idx;planLevels.forEach((x,i)=>x.classList.toggle('active',i===p));app.querySelectorAll('.plan-progress').forEach(x=>x.style.width=`${p*34}%`);app.querySelectorAll('[data-plan-label]').forEach(x=>x.textContent=plans[p].label);app.querySelectorAll('[data-plan-title]').forEach(x=>x.textContent=plans[p].title);app.querySelectorAll('[data-plan-desc]').forEach(x=>x.textContent=plans[p].desc);app.querySelectorAll('[data-feature]').forEach(x=>x.classList.toggle('on',Number(x.dataset.feature)<plans[p].features));};planLevels.forEach((x,i)=>x.addEventListener('click',()=>setPlan(i)));setInterval(()=>setPlan((p+1)%3),3800);}

/* Hash navigation after dynamic render */
if(location.hash){requestAnimationFrame(()=>setTimeout(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:'smooth',block:'start'}),90));}
})();
