(()=>{
const LOGIN='https://www.spxos.com.br/entrar';
const ASSETS={hoje:'https://i.imgur.com/X2CZmwp.png',conversas:'https://i.imgur.com/Zn3UeSG.png',crm:'https://i.imgur.com/JMlzJcx.png',config:'https://i.imgur.com/fsdZG1P.png',desempenho:'https://i.imgur.com/RVcNuPf.png'};
const app=document.querySelector('#app');
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;

const img=(src,alt,cls='',priority=false,mark='')=>`<figure class="screen ${cls}"><img src="${src}" alt="${alt}" width="1672" height="941" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async" referrerpolicy="no-referrer">${mark?`<span class="screen-mark" style="${mark}"></span>`:''}</figure>`;
const cta=(title='Veja o SPX OS aplicado à sua operação.')=>`<section class="closing"><div class="wrap closing-inner"><div><h2>${title}</h2><p>Conheça a estrutura antes de decidir como ela deve entrar na sua empresa.</p></div><a class="button button-light" href="/planos">Conhecer planos</a></div></section>`;

const home=()=>`<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="label">SPX OS</span><h1>Veja onde a operação trava. Saiba o que fazer agora.</h1><p>CRM comercial, WhatsApp, jornada e desempenho conectados para mostrar o que entrou, quem assumiu, onde parou e o que precisa acontecer em seguida.</p><div class="hero-actions"><a class="button button-primary" href="/produto">Conhecer o produto</a><a class="button button-secondary" href="/planos">Ver planos</a></div><div class="hero-proof"><span><i></i>Marketing e comercial na mesma leitura</span><span><i></i>Operação por equipe e unidade</span><span><i></i>WhatsApp dentro do contexto comercial</span></div></div><div>${img(ASSETS.hoje,'Tela Hoje do SPX OS','large',true,'left:72%;top:32%')}</div></div></section>
<section class="statement"><div class="wrap statement-row"><div><small>Marketing</small><strong>Não termina no lead gerado.</strong></div><div><small>Comercial</small><strong>Não começa procurando histórico.</strong></div><div><small>Gestão</small><strong>Não deveria depender de dez relatórios.</strong></div></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">Um sistema. Quatro partes da mesma operação.</h2><p>O SPX OS não empilha ferramentas. Ele organiza a passagem da oportunidade entre entrada, conversa, execução e decisão.</p></div><div class="product-strip reveal"><a href="/produto#crm"><small>01</small><strong>CRM Comercial</strong><span>Etapa, responsável e próximo movimento.</span></a><a href="/produto#whatsapp"><small>02</small><strong>WhatsApp</strong><span>Conversa junto do contexto da oportunidade.</span></a><a href="/produto#desempenho"><small>03</small><strong>Desempenho</strong><span>Conversão, perda e leitura gerencial.</span></a><a href="/produto#multiunidade"><small>04</small><strong>Multiunidade</strong><span>Regras, equipes e unidades sob o mesmo padrão.</span></a></div></div></section>
<section class="section soft"><div class="wrap feature-row"><div class="feature-copy reveal"><h2>A conversa modifica a operação.</h2><p>Quando atendimento e CRM estão separados, o contexto se perde. No SPX OS, a conversa acontece junto da etapa, do responsável e da próxima ação.</p><ul class="feature-list"><li>Contato e oportunidade no mesmo ambiente</li><li>Histórico comercial visível durante o atendimento</li><li>Próxima ação sem depender de memória</li></ul><a class="button button-secondary" style="margin-top:26px" href="/produto#whatsapp">Ver como funciona</a></div><div class="reveal">${img(ASSETS.conversas,'Central de conversas do SPX OS')}</div></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">O volume importa. O caminho importa mais.</h2><p>Uma operação só fica legível quando é possível acompanhar a passagem da oportunidade até o fechamento — e identificar onde a conversão perde força.</p></div><div class="metric-line reveal"><div><small>Leads</small><strong>412</strong><em>entrada</em></div><div><small>Contatados</small><strong>266</strong><em>64,6%</em></div><div><small>Agendados</small><strong>166</strong><em>62,4%</em></div><div><small>Compareceram</small><strong>102</strong><em>61,4%</em></div><div><small>Fecharam</small><strong>64</strong><em>62,7%</em></div></div></div></section>
<section class="quote-block"><div class="wrap"><h2>“Feeling é ego. Clareza é certeza.”</h2><p>O papel do sistema não é produzir mais informação. É reduzir a distância entre o que aconteceu e a decisão que precisa ser tomada.</p></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">A mesma operação. Leituras diferentes para quem precisa agir.</h2><p>Marketing, comercial, diretoria e redes não precisam de quatro sistemas. Precisam enxergar a mesma realidade pelo recorte certo.</p></div><div class="solution-band reveal"><div><small>Solução</small><strong>Marketing</strong></div><div><h2>Entender o que entrou — e o que realmente avançou.</h2><p>Origem, volume e qualidade deixam de terminar na geração do lead.</p></div></div><div class="solution-band reveal"><div><small>Solução</small><strong>Comercial</strong></div><div><h2>Saber quem precisa de atenção antes de procurar no histórico.</h2><p>Retorno, agenda, proposta e próxima ação passam a fazer parte da rotina visível.</p></div></div><div class="solution-band reveal"><div><small>Solução</small><strong>Diretoria</strong></div><div><h2>Ver conversão, receita e gargalo sem montar uma planilha nova.</h2><p>Uma leitura executiva sobre a mesma jornada operada pelas equipes.</p></div></div></div></section>${cta()}`;

const product=()=>`<section class="page-hero"><div class="wrap page-hero-grid"><div><span class="label">Produto</span><h1>O produto começa onde uma oportunidade entra — e termina onde uma decisão fica clara.</h1></div><p>Em vez de repetir telas, esta página mostra a lógica do sistema: como a oportunidade muda de estado, como a conversa altera a jornada e como o desempenho vira leitura de gestão.</p></div></section>
<section class="section soft" id="crm"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">CRM Comercial</h2><p>O pipeline deixa de ser uma coleção de cards e passa a mostrar o próximo movimento de cada oportunidade.</p></div><div class="flow reveal" data-flow><div class="flow-step active"><small>Entrada</small><strong>Novo lead</strong><span>Origem registrada</span></div><div class="flow-step"><small>Ação 1</small><strong>Contato</strong><span>Responsável definido</span></div><div class="flow-step"><small>Ação 2</small><strong>Qualificação</strong><span>Interesse e procedimento</span></div><div class="flow-step"><small>Ação 3</small><strong>Agendamento</strong><span>Data e confirmação</span></div><div class="flow-step"><small>Saída</small><strong>Fechamento</strong><span>Valor e resultado</span></div></div><div class="feature-row reveal"><div class="feature-copy"><h2>O contexto acompanha a oportunidade.</h2><p>Unidade, origem, procedimento, responsável e valor potencial ficam associados à jornada — sem depender de uma planilha paralela.</p><ul class="feature-list"><li>Etapa atual visível</li><li>Responsabilidade definida</li><li>Próximo movimento explícito</li><li>Filtros por origem, equipe e procedimento</li></ul></div>${img(ASSETS.crm,'CRM Comercial do SPX OS','',false,'left:52%;top:44%')}</div></div></section>
<section class="section" id="whatsapp"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">WhatsApp integrado</h2><p>A conversa não fica fora da operação. Ela muda a etapa, atualiza a próxima ação e mantém o histórico comercial no mesmo contexto.</p></div><div class="wa-stage reveal" data-wa><div class="wa-thread"><div class="wa-head"><strong>Juliana Pereira · Implante Unitário</strong></div><div class="messages"><div class="message">Olá! Gostaria de agendar uma avaliação.</div><div class="message out">Claro. Temos terça-feira às 10h. Posso reservar?</div><div class="message">Pode sim. Obrigada!</div><div class="message out">Perfeito. Agendamento confirmado. ✅</div></div></div><aside class="wa-context"><h3>Contexto da oportunidade</h3><div class="wa-field"><small>Etapa</small><strong data-wa-stage>Contato</strong><span class="wa-state" data-wa-state>Aguardando ação</span></div><div class="wa-field"><small>Responsável</small><strong>Equipe comercial</strong></div><div class="wa-field"><small>Próxima ação</small><strong data-wa-next>Confirmar disponibilidade</strong></div><button class="wa-action" type="button">Simular agendamento</button><p class="wa-note">A demonstração usa uma interação simples para mostrar causa → efeito, sem substituir o produto real.</p></aside></div></div></section>
<section class="section soft" id="desempenho"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">Desempenho</h2><p>O dashboard só faz sentido quando ajuda a apontar onde investigar. A leitura começa no caminho da oportunidade, não no gráfico.</p></div><div class="metric-line reveal"><div><small>Oportunidades</small><strong data-count="412">0</strong><em>entrada</em></div><div><small>Contatados</small><strong data-count="266">0</strong><em>64,6%</em></div><div><small>Agendados</small><strong data-count="166">0</strong><em>62,4%</em></div><div><small>Compareceram</small><strong data-count="102">0</strong><em>61,4%</em></div><div><small>Fecharam</small><strong data-count="64">0</strong><em>62,7%</em></div></div><div class="feature-row reverse reveal">${img(ASSETS.desempenho,'Desempenho do SPX OS')}<div class="feature-copy"><h2>O ponto de atenção precisa aparecer antes do próximo investimento.</h2><p>No exemplo exibido, a etapa de comparecimento merece investigação antes de simplesmente aumentar o volume de entrada.</p><ul class="feature-list"><li>Conversão etapa a etapa</li><li>Leitura por canal e procedimento</li><li>Desempenho por responsável</li><li>Valor fechado por período</li></ul></div></div></div></section>
<section class="section" id="multiunidade"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">Multiunidade</h2><p>Crescer não deveria significar criar várias versões diferentes do mesmo processo.</p></div><div class="feature-row reveal"><div class="feature-copy"><h2>Uma regra comum, com leitura por unidade.</h2><p>Equipe, acessos, distribuição, procedimentos e motivos de perda podem seguir a mesma estrutura sem apagar a realidade de cada filial.</p><ul class="feature-list"><li>Organização e unidade</li><li>Regras de distribuição</li><li>Acessos por função</li><li>Cadastros operacionais centralizados</li></ul></div>${img(ASSETS.config,'Configurações e governança do SPX OS')}</div></div></section>${cta('Conheça o produto por dentro — com a sua operação como contexto.')}`;

const solutions=()=>`<section class="page-hero"><div class="wrap page-hero-grid"><div><span class="label">Soluções</span><h1>O mesmo dado precisa responder perguntas diferentes.</h1></div><p>Marketing quer saber o que avançou. Comercial precisa saber o que fazer agora. Diretoria quer localizar gargalo e impacto. Redes precisam comparar sem perder padrão.</p></div></section>
<section class="section"><div class="wrap"><div class="solution-band reveal" id="marketing"><div><small>01</small><strong>Marketing</strong></div><div><h2>Da origem até o que o comercial realmente conseguiu trabalhar.</h2><p>A análise deixa de terminar no CPL e passa a acompanhar a oportunidade depois da entrada.</p><div class="solution-proof"><span><b>412</b>oportunidades</span><span><b>266</b>contatadas</span><span><b>64</b>fechamentos exibidos</span></div></div></div><div class="solution-band reveal" id="comercial"><div><small>02</small><strong>Comercial</strong></div><div><h2>Prioridade antes de volume.</h2><p>Interesses sem agenda, retornos vencidos, confirmações e faltosos precisam aparecer como trabalho do dia — não como informação escondida no histórico.</p><div class="solution-proof"><span><b>14</b>sem agenda</span><span><b>6</b>retornos vencidos</span><span><b>9</b>a confirmar</span></div></div></div><div class="solution-band reveal" id="diretoria"><div><small>03</small><strong>Diretoria</strong></div><div><h2>Uma leitura executiva que nasce da mesma operação que o time executa.</h2><p>Conversão, receita, canal, procedimento, unidade e responsável deixam de depender de relatórios desconectados.</p><div class="solution-proof"><span><b>5</b>etapas de leitura</span><span><b>1</b>verdade operacional</span></div></div></div><div class="solution-band reveal" id="redes"><div><small>04</small><strong>Redes e filiais</strong></div><div><h2>Comparar unidades sem criar empresas diferentes dentro da mesma marca.</h2><p>Padronização de processo e leitura local convivem dentro da mesma estrutura de governança.</p><div class="solution-proof"><span><b>1</b>padrão</span><span><b>N</b>unidades</span></div></div></div></div></section>${cta('Encontre o recorte que mais se parece com a sua operação.')}`;

const about=()=>`<section class="about-hero"><div class="wrap about-grid"><div><span class="label" style="color:var(--gold)">Sobre</span><h1>O sistema surgiu para tirar pontos de interrogação da operação.</h1></div><div><p>Quem gerou a oportunidade? Quem assumiu? Onde ela parou? Quanto avançou? O que precisa acontecer agora?</p><p>O SPX OS foi pensado para transformar essas perguntas em responsabilidade, etapa, dado e próxima ação.</p></div></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">A origem é simples: trazer clareza para a operação.</h2><p>Marketing, vendas e gestão costumam enxergar fragmentos diferentes da mesma realidade. O sistema nasce para reduzir essa distância.</p></div><div class="question-grid reveal"><div class="question-row"><i>?</i><strong>Quem gerou esta oportunidade?</strong><span>Origem registrada.</span></div><div class="question-row"><i>?</i><strong>Quem ficou responsável?</strong><span>Responsabilidade definida.</span></div><div class="question-row"><i>?</i><strong>Onde ela parou?</strong><span>Etapa visível.</span></div><div class="question-row"><i>?</i><strong>Quanto avançou?</strong><span>Conversão mensurada.</span></div><div class="question-row"><i>?</i><strong>O que precisa acontecer agora?</strong><span>Próxima ação clara.</span></div></div></div></section>
<section class="section dark"><div class="wrap"><div class="section-head reveal"><h2 class="section-title">A tecnologia é a estrutura. A tese continua sendo gestão.</h2><p>O produto existe para organizar leitura, responsabilidade e direção. O objetivo final não é produzir mais dashboards: é reduzir ambiguidade na decisão.</p></div><div class="principles reveal"><div><small>01</small><strong>Operação</strong><p>Entrada, conversa, agenda, acompanhamento e responsabilidade.</p></div><div><small>02</small><strong>Leitura</strong><p>Conversão, perda, canal, procedimento, responsável e unidade.</p></div><div><small>03</small><strong>Direção</strong><p>Prioridade, governança, padronização e decisão executiva.</p></div></div></div></section>
<section class="quote-block"><div class="wrap"><h2>“Feeling é ego. Clareza é certeza.”</h2><p>Essa frase resume melhor o produto do que qualquer lista de funcionalidades.</p></div></section>${cta('Se a operação ainda depende de perguntas demais, vale ver o sistema funcionando.')}`;

const plans=()=>`<section class="page-hero"><div class="wrap plans-intro"><div><span class="label">Planos</span><h1>A estrutura cresce com a complexidade da operação.</h1></div><p>Os níveis abaixo organizam a lógica comercial do produto. Preço, usuários e limites finais devem ser definidos em proposta conforme operação, unidades e necessidade de governança.</p></div></section>
<section class="section" style="padding-top:30px"><div class="wrap"><div class="plans-table reveal"><div class="plan-row head"><div></div><div><strong>Operação</strong><span>Para uma equipe que precisa organizar a rotina comercial.</span></div><div><strong>Gestão</strong><span>Para marketing e comercial trabalhando como uma operação.</span></div><div><strong>Escala</strong><span>Para redes, filiais e estruturas com maior governança.</span></div></div><div class="plan-row"><div>CRM Comercial</div><div class="check">✓</div><div class="check">✓</div><div class="check">✓</div></div><div class="plan-row"><div>WhatsApp integrado</div><div class="check">✓</div><div class="check">✓</div><div class="check">✓</div></div><div class="plan-row"><div>Jornada e agenda</div><div class="check">✓</div><div class="check">✓</div><div class="check">✓</div></div><div class="plan-row"><div>Indicadores operacionais</div><div class="check">✓</div><div class="check">✓</div><div class="check">✓</div></div><div class="plan-row"><div>Desempenho e conversão</div><div class="dash">—</div><div class="check">✓</div><div class="check">✓</div></div><div class="plan-row"><div>Distribuição e automação</div><div class="dash">—</div><div class="check">✓</div><div class="check">✓</div></div><div class="plan-row"><div>Multiunidade</div><div class="dash">—</div><div class="dash">—</div><div class="check">✓</div></div><div class="plan-row"><div>Governança por função</div><div class="dash">—</div><div class="dash">—</div><div class="check">✓</div></div></div><div class="plan-cta"><a class="button button-primary" href="${LOGIN}">Já sou cliente</a></div></div></section>
<section class="quote-block"><div class="wrap"><h2>Você não precisa contratar a complexidade que ainda não existe.</h2><p>O plano deve acompanhar equipe, unidade e nível de governança — não forçar uma empresa pequena a operar como uma rede.</p></div></section>${cta('Escolha o nível pela operação. A proposta fecha o restante.')}`;

const pages={home,produto:product,solucoes:solutions,sobre:about,planos:plans};
function normalizeRoute(){const q=new URLSearchParams(location.search).get('route');const p=location.pathname.replace(/^\/+|\/+$/g,'');return q||p||'home'}
function cleanUrl(route,hash=''){if(route==='home') return '/'+hash;return '/'+route+hash}
function setMeta(route){const data={home:['SPX OS — Clareza para operar e crescer','CRM comercial, WhatsApp, jornada e desempenho conectados para mostrar onde a operação trava e o que precisa acontecer agora.'],produto:['Produto | SPX OS','Conheça CRM Comercial, WhatsApp integrado, desempenho e multiunidade dentro do SPX OS.'],solucoes:['Soluções | SPX OS','Soluções do SPX OS para marketing, comercial, diretoria, redes e filiais.'],sobre:['Sobre | SPX OS','Por que o SPX OS surgiu: transformar dúvidas operacionais em responsabilidade, etapa, leitura e próxima ação.'],planos:['Planos | SPX OS','Conheça a lógica dos planos Operação, Gestão e Escala do SPX OS.']}[route]||['SPX OS','SPX OS'];document.title=data[0];document.querySelector('meta[name=description]')?.setAttribute('content',data[1])}
function render(route,hash='',push=false){route=pages[route]?route:'home';const run=()=>{app.innerHTML=pages[route]();document.body.dataset.route=route;setMeta(route);updateNav(route);wirePage();if(push) history.pushState({route},'',cleanUrl(route,hash));else if(new URLSearchParams(location.search).has('route')) history.replaceState({route},'',cleanUrl(route,hash));requestAnimationFrame(()=>{if(hash){document.querySelector(hash)?.scrollIntoView({behavior:'auto',block:'start'})}else scrollTo(0,0)})};if(document.startViewTransition&&!reduceMotion) document.startViewTransition(run);else run()}
function updateNav(route){document.querySelectorAll('.nav-link').forEach(a=>a.removeAttribute('aria-current'));document.querySelectorAll('.nav-trigger').forEach(b=>b.classList.remove('current'));if(route==='sobre'||route==='planos') document.querySelector(`.nav-link[href="/${route}"]`)?.setAttribute('aria-current','page');if(route==='produto') document.querySelector('.product-panel')?.previousElementSibling?.classList.add('current');if(route==='solucoes') document.querySelector('.solution-panel')?.previousElementSibling?.classList.add('current')}
function wirePage(){const reveals=[...app.querySelectorAll('.reveal')];if(reduceMotion) reveals.forEach(x=>x.classList.add('visible'));else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -8% 0px'});reveals.forEach(x=>io.observe(x))}
const heroScreen=app.querySelector('.hero .screen');if(heroScreen) setTimeout(()=>heroScreen.classList.add('is-active'),500);
const flow=app.querySelector('[data-flow]');if(flow&&!reduceMotion){const steps=[...flow.querySelectorAll('.flow-step')];let i=0;const cycle=()=>{steps.forEach((s,n)=>s.classList.toggle('active',n===i));i=(i+1)%steps.length};cycle();setInterval(cycle,1700)}
const wa=app.querySelector('[data-wa]');if(wa){const msgs=[...wa.querySelectorAll('.message')];msgs.forEach((m,i)=>setTimeout(()=>m.classList.add('show'),reduceMotion?0:350+i*420));const btn=wa.querySelector('.wa-action');btn?.addEventListener('click',()=>{wa.querySelector('[data-wa-stage]').textContent='Agendamento';wa.querySelector('[data-wa-state]').textContent='Confirmado';wa.querySelector('[data-wa-next]').textContent='Acompanhar comparecimento';btn.textContent='Agendamento realizado ✓';btn.classList.add('done')})}
const counts=[...app.querySelectorAll('[data-count]')];if(counts.length){const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const n=Number(e.target.dataset.count);if(reduceMotion){e.target.textContent=n;io.unobserve(e.target);return}const start=performance.now(),dur=700;const tick=t=>{const p=Math.min(1,(t-start)/dur);e.target.textContent=Math.round(n*p);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);io.unobserve(e.target)}),{threshold:.4});counts.forEach(x=>io.observe(x))}}
function wireGlobal(){const menuBtn=document.querySelector('#menuBtn'),nav=document.querySelector('#mainNav');menuBtn?.addEventListener('click',()=>nav?.classList.toggle('open'));document.querySelectorAll('.nav-trigger').forEach(btn=>btn.addEventListener('click',()=>{if(innerWidth<=1050){const d=btn.closest('.nav-dropdown');d.classList.toggle('open');btn.setAttribute('aria-expanded',d.classList.contains('open'))}}));document.addEventListener('click',e=>{const a=e.target.closest?.('a[href]');if(!a||a.target==='_blank'||a.hasAttribute('download'))return;const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;const route=u.pathname.replace(/^\/+|\/+$/g,'')||'home';if(!pages[route])return;e.preventDefault();nav?.classList.remove('open');document.querySelectorAll('.nav-dropdown.open').forEach(x=>x.classList.remove('open'));render(route,u.hash,true)});addEventListener('popstate',()=>render(normalizeRoute(),location.hash,false))}
wireGlobal();render(normalizeRoute(),location.hash,false);
})();